export default {
    logo_img: require('../assets/images/login.jpg'),
    heart: require('../assets/images/heart.png'),
    down_arrow: require('../assets/images/down-arrow.png'),
    sort_down: require('../assets/images/sort-down.png'),
    menu: require('../assets/images/menu.png'),
    home: require('../assets/images/home.png'),
    plus: require('../assets/images/plus.png'),
    minus: require('../assets/images/minus.png'),
    zoom: require('../assets/images/zoom.png'),
    hand: require('../assets/images/hand.png'),
    bed: require('../assets/images/bed.png'),
    card_line: require('../assets/images/line.png'),
    car: require('../assets/images/car.png'),
    galary: require('../assets/images/gallery.png'),
    user: require('../assets/images/user.png'),
    bell: require('../assets/images/bell.png'),
    setting: require('../assets/images/setting.png'),
    flag: require('../assets/images/flag.png'),
    header_menu: require('../assets/images/header_menu.png'),
}